name: Build Geode Mod

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Geode Mod
      uses: geode-sdk/build-geode-mod@main
      with:
        platforms: "windows,android,ios"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MCR-geode-mod
        path: build/*.geode
        
